### ISSUE TITLE
Uncaught TypeError: Cannot read property 'crypto' of undefined

### ISSUE THREAD

**Issue by kamipatel** [aws/amazon-connect-streams#1]
I created JS file using make command. Getting above error. Please advice. Thanks!

**Comment by autrey** [comment]
Can you provide some more information about your issue? Maybe some of your code? It's tough to diagnose without context :-)

**Comment by AshleyOboe** [comment]
When I include the js file in index.html I get the errors below. (Clarification - there is just one file to create for streams correct?  The readme references two different js name conventions).  

  <script src="assets/amazon-connect-v1.1.1-2-g0b8509c.js"></script>


Runtime Error
Uncaught (in promise): TypeError: Cannot read property 'DocumentClient' of undefined TypeError: Cannot read property 'DocumentClient' of undefined at new DynamoDB 

Ionic Framework: 3.4.2
Ionic App Scripts: 1.3.7
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.11.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36

**Comment by sromocki** [comment]
I know this is an old issue, but I got this error when I tried to run the amazon connect JS through Babel.  You need to exclude sending it through babel with something like the below:

```javascript
{
    test: /\.(js)$/,
    exclude: /(node_modules|src\/amazon-connect-v1\.1\.0\.js)/,
    use: [
      'babel-loader'
    ]
}
```

**Comment by jagadeeshaby** [comment]
Please feel free to reopen if the issue persists.
