### ISSUE TITLE
X-Frame-Options sameorigin

### ISSUE THREAD

**Issue by abearden** [aws/amazon-connect-streams#10]
Hasn't been answered on the AWS forum, hoping I can get an answer here. Setting up a test for Connect with a bare page. Single DIV, amazon-connect.js, and the connect.core.initCCP call. Regardless of whether I set ccpUrl to "https://**domain**.awsapps.com/connect/home",  "https://**domain**.awsapps.com/connect/login", or "https://**domain**.awsapps.com/connect/ccp" as provided in the administration console, I receive:

Refused to display 'https://**domain**.awsapps.com/connect/home' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
amazon-connect.js:20361 GET https:///**domain**.awsapps.com/connect/home net::ERR_BLOCKED_BY_RESPONSE

Removing the path tries to redirect the entire page and fails with "Access Error
This application has not been enabled for your directory. Please contact your Administrator for more details." Trying "https://**domain**.awsapps.com/connect" populates the iframe with an AccessDenied XML response, despite whitelisting the domain hosting the test.

What am I missing?

For reference:
	connect.core.initCCP(awsConnect, {
			ccpUrl:        "https://**domain**.awsapps.com/connect/ccp", 
			loginPopup:    true,  
			softphone:     {      
				disableRingtone:  false
			}
	});

**Comment by abearden** [comment]
And it figures, after asking for help the answer comes. The correct url is "https://**domain**.awsapps.com/connect/ccp#", the pound sign being vastly important for some reason.

**Comment by atekie** [comment]
I am receiving the same error even when using https://domain.awsapps.com/connect/ccp# as the url.  I am including the single js file built, plus I have whitelisted the domain.  What am I missing?

**Comment by autrey** [comment]
@atekie Hopefully this isn't a stupid question, but did you whitelist the domain as https (which is required)?

**Comment by atekie** [comment]
@autrey yes we did whitelist the domain with https, thanks for chiming in!

**Comment by stupidasker** [comment]
we are facing same error , after doing every thing on amazon connect integration.

<!DOCTYPE html> 
<html> 
<head> 
<title>Amazone Connect</title> 
</head> 
<body> 
<div id="containerDiv" ></div> 
</body> 
<script type="text/javascript" src="{{ asset('js/amazon-connect-v1.2.0.js') }}"></script> 
<script type="text/javascript"> 
connect.core.initCCP(containerDiv, { 
ccpUrl: 'https://INSTANCENAME.awsapps.com/connect/ccp#', 
loginPopup: true, 
softphone: { 
allowFramedSoftphone: true 
} 
}); 
</script> 
</html>

**Comment by MercedesFiore** [comment]
I have the same **_intermittent_** issue.

Refused to display 'https://domain.awsapps.com/connect/login?landat=%2Fconnect%2Fccp#/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

`connect.core.initCCP(containerDiv, {
   ccpUrl:        'https://domain.awsapps.com/connect/ccp#/',       
   loginPopup:    true,          
   softphone:     {             
      disableRingtone:  false,    
      //ringtoneUrl: ringtoneUrl  
	   allowFramedSoftphone: true
   }
});`

As a work around, I've added a login button to the container div - which I hide when agent connects. This is pretty clunky. Looking for a better solution.

**Comment by sromocki** [comment]
I don't get this issue locally, but I do get this issue in a staging server that I've created.
The successful request, locally, looks like this:
![successful_request](https://user-images.githubusercontent.com/2022994/32387618-09a629f8-c093-11e7-9e3c-bb75a8e6b638.png)

The same request on the staging server where I get the 'sameorigin' error, looks like this:
![request_where_i_get_error](https://user-images.githubusercontent.com/2022994/32387268-e94070d4-c091-11e7-9df3-fdbd4f45b09a.png)

The only difference I see is some cookie key/values missing: username=; lily-auth-prod-iad=;
Not sure why those get populated locally vs on the staging server.

**Comment by AshishYW** [comment]
hi ,

I am also facing same issue of X-Frame-Options' to 'sameorigin'
Is there any solution for th

**Comment by mschersten** [comment]
Not sure how relevant this is to all the different problems here, but make sure that you not only whitelisted the custom panel as https, but that you are also accessing it that way as well.  I got lazy and tried to load s3.amazonaws.com/mybucket, without https, and from some computers is loads securely by default, others not.

**Comment by weynhamz** [comment]
Encountered this today while integrating with Salesforce, nearly given up, it turns out that need to add the Virualforce page domain used in CCP control panel to the Connect Approved origins list.

**Comment by Tedric** [comment]
I have encountered the same issue and ended up resolving the issue by added https://XXXXXXXX--amazonconnect.ap1.visual.force.com/ to the **Approved origins** in the **Application integration** section of **Amazon Connect**.

**Comment by satyendragupta** [comment]
> And it figures, after asking for help the answer comes. The correct url is "https://**domain**.awsapps.com/connect/ccp#", the pound sign being vastly important for some reaso

**Comment by leohunter982** [comment]
It was interesting to prepare for my IT exam from [SAA-C02 Practice Exam Questions](https://www.amazonawsdumps.com/saa-c02-dumps.html). I didn’t deliberate too much hard but I studied cool while going through this compact guide. All the information about the field was condensed in it. AWS-Certified-Cloud-Practitioner Exam covered all the aspects very well. I say cheers for this great help.

**Comment by vtrofin** [comment]
Hi there, I'm having the same issue with connect streams api as @old-square-eyes mentioned above. Did anyone figure out a workaround for this issue? The error says: 
 > Refused to display 'https://`<your-instance-name>`.awsapps.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
<img width="661" alt="Screen Shot 2023-06-30 at 17 26 55" src="https://github.com/amazon-connect/amazon-connect-streams/assets/18513968/7e66e21e-5d62-4707-9b64-62ec699152b8">
 
 - browser: Chrome Version 114.0.5735.133 (Official Build) (arm64)
 - app: React 18 and Vite js; I'm running the app on `https://localhost:3000` and I have the domain in the list of approved domains
 
<img width="1112" alt="Screen Shot 2023-06-30 at 17 26 05" src="https://github.com/amazon-connect/amazon-connect-streams/assets/18513968/8465bc26-dcb9-4265-8663-ad3354f898e2">


 - dependencies:
```
 "dependencies": {
    "amazon-connect-streams": "^2.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.14.0",
    "zod": "^3.21.4"
  },
```
- I basically followed this [example implementation](https://github.com/aws-samples/ccp-react-dashboard-example/blob/1b79b6e0d925b2c712db041948e698e6c63ce6bc/ccp-ui/src/components/ConnectCCP.jsx#L11-L42)
- My code:
```ts
// App.tsx
import { useCallback } from "react"

import "./App.css"
import ConnectCCP from "@components/core/ConnectCCP"

function App() {
  // Avoid re-rendering ConnectCCP
  const CCP = useCallback(() => <ConnectCCP />, [])

  return (
    <div>
      <h1>Vite + React</h1>
      <CCP />
    </div>
  )
}

export default App

```

```ts
// ConnectCCP.tsx
import { useConnectCCPHook } from "./hook"
import { memo } from "react"

const ConnectCCP = () => {
  const { ref } = useConnectCCPHook()

  return (
    <div ref={ref} className={"w-full h-full min-w-[400px] min-h-[480px]"}>
      test connect container
    </div>
  )
}

export default memo(ConnectCCP)

```

```ts
// hook.ts
import { useRef, useEffect, MutableRefObject } from "react"
import { config } from "@config/index"

import "amazon-connect-streams"

interface ConnectCCPType {
  ref: MutableRefObject<HTMLDivElement | null>
}

const useConnectCCPHook = (): ConnectCCPType => {
  const ref = useRef<HTMLDivElement | null>(null)

  const ccpUrl = `https://${config.connectInstanceAlias}.my.connect.aws/connect/ccp-v2`

  useEffect(() => {
    try {
      window.connect.core.initCCP(ref.current as HTMLElement, {
        ccpUrl,
        region: config.connectInstanceRegion,
        loginPopup: false,
        loginPopupAutoClose: true,
        loginOptions: { autoClose: true },
        softphone: { allowFramedSoftphone: true },
        pageOptions: {
          enableAudioDeviceSettings: true,
          enablePhoneTypeSettings: true,
        },
        ccpAckTimeout: 5000,
        ccpSynTimeout: 3000,
        ccpLoadTimeout: 10000,
      })
    } catch (err) {
      console.log("err --->", err)
    }

    return () => {
      // handle React 18 double mount of useEffect in dev mode
      window.connect.core.terminate()
      if (ref.current?.children) {
        const targetNode = ref.current.children.namedItem("Amazon Connect CCP")

        if (targetNode) {
          ref.current?.removeChild(targetNode)
        }
      }
    }
  }, [])

  return { ref }
}

export { useConnectCCPHook }

```

**Comment by copremesis** [comment]
Why is this issue closed?
