### ISSUE TITLE
Is there a way to hide the hang up button in the phone panel?

### ISSUE THREAD

**Issue by waqar125** [aws/amazon-connect-streams#100]
We have a requirement to create our own hang up button.
however, we want to hide the built hang up button in CCP?

is it possible?

**Comment by jagadeeshaby** [comment]
There is no easy way to do this as CCP is rendered within iframe and the CSP rules may not allow it and also it's not a standard practice. 

I would suggest to Build your own CCP by consuming streams - recommended 

And yes you can always use CSS hacks to do the same - Not recommended
 - Position a div(element) on top of this button - Hacky and not extendable 
 - https://stackoverflow.com/questions/217776/how-to-apply-css-to-iframe
