### ISSUE TITLE
How can I read the agent After call work (ACW) timeout in stream js?

### ISSUE THREAD

**Issue by scyforce** [aws/amazon-connect-streams#107]
since the admin can assign a after call timeout for each user, how can I read it in stream.js? also how can I read the contact timeout for each agent (the time between the agent assigned a call and he accepts the call) and the overall contact timeout(the overall time a call in a queue) in stream.js?

**Comment by jagadeeshaby** [comment]
As of today these informations are not available on StreamJS. Unfortunately i do not have an ETA on getting this soon.

I have created the tracking issue internally to prioritize this.  

Thanks.

**Comment by mikehanney** [comment]
Is there any update on getting the after call work timeout from the stream?

**Comment by nmiddleweek** [comment]
Hello - Is there an update on this please? I'm very surprised After call work (ACW) timeout isn't available from ```agent.getConfiguration()```

Is there an another approach to getting this value so we can use it on our Custom CCP?

Thanks
