### ISSUE TITLE
agent.onNotRoutable not invoked when switching from one not routable state to another

### ISSUE THREAD

**Issue by aguecida** [aws/amazon-connect-streams#110]
The `agent.onNotRoutable` event only gets triggered in the following scenarios:

1. Online -> Not Routable
2. Offline -> Not Routable

Since multiple Not Routable states can be configured in Connect, we should also be notified in the case that an agent switches states from Not Routable -> Not Routable.

**Comment by jagadeeshaby** [comment]
I believe it's intentional as changing between Not Routable -> Not Routable does not change the routing type hence the behavior. 

You may want to consider onStateChange on agent which indicates the state change irrespective of the routing type. (routable/non-routable/offline). 

Is there any specific use case for this ask? more details would be helpful.

**Comment by aguecida** [comment]
In that scenario an onStateChange event would be desired.

We have a lot of use cases where we use specific Not Routable states to control application behaviors. We use the Connect state control to control delivery of our own custom tasks to an agent. In a normal flow, if an agent goes Available they will be ready to handle both phone tasks as well as our own tasks (which ever is delivered first). We use one Not Routable state as a pseudo "Available" state, where when an agent switches to this state they will be ready to receive our custom tasks but not receive phone calls. Currently, if an agent is in a Not Routable Break state and switches to this Not Routable "Available" state, we will not get notified and our application can't behave accordingly.

As you suggested, I think a new agent event (i.e. onStateChange) that is triggered whenever a state change occurs (regardless of whether it is initiated by the system programmatically or by the user manually) provides the most flexibility for third party developers and would cover all our use cases.

**Comment by jagadeeshaby** [comment]
Thanks!.  feel free to reopen if needed

**Comment by aguecida** [comment]
Hey @jagadeeshaby,

Do you think an "onStateChange" event as discussed above will be available through the Streams API anytime soon? Or is there a better place to post a feature request like this?

**Comment by jagadeeshaby** [comment]
Oh sorry i forgot to mention.  we have this handler available on agent today.  

sample usage.  
```
new connect.Agent().onStateChange((...args) => {
     console.log(args, new connect.Agent().getState());
})
```

**Comment by aguecida** [comment]
Great, tried that code and it is working for me. Thanks!

Noticed this event handler is missing in the documentation (as well as the TypeScript definition file). Should I open a separate issue for that?

**Comment by joesomprakash** [comment]
> Thanks!. feel free to reopen if needed

I need help on this. agent on state change when changed my function doesn't work properly
