### ISSUE TITLE
Contact event not getting triggered

### ISSUE THREAD

**Issue by pukhrajbal** [aws/amazon-connect-streams#12]
When a phone call is received subscription events for contact.onIncoming (also onMissed) are not getting triggered. As a result caller number cannot be accessed while the phone is ringing. 
ContactData is available once the call completes on onEnded event.

**Comment by clegeard** [comment]
Any feedback on this, I am experiencing the same problem, contact.onIncoming is not triggered.
Thanks

**Comment by KDLGates** [comment]
Also piling on to this. onIncoming never fires (haven't tested onMissed). This is posing a significant problem to our integration efforts, which are very important to our work -- we have big plans.

We placed an AWS support case for this issue, which is still active.

Amazon professionals, please save us! :-)

**Comment by sromocki** [comment]
I don't use that handler.  Instead I've done it like this:
```
global.connect.contact(function(contact) {
        var contactId = contact.getContactId();
        var attributeObj = contact.getAttributes();
        var isInbound = contact.isInbound();
        
        contact.onConnected(function(){
            if(isInbound){
                var agentConn = contact.getAgentConnection();
                var connectionId = agentConn.getConnectionId();
                var aniObj = attributeObj.MDN;
                var ani = aniObj ? aniObj["value"] : null;
                var properties = {};
                properties[telephonyConstants.ANI] = ani;
                properties[telephonyConstants.MDN] = ani;
                properties[telephonyConstants.CALLIDENTIFIER] = contactId;
                properties[telephonyConstants.PROVIDERCALLID] = connectionId;
            
                store.dispatch(inboundCallEvent(properties));
            }
        });
    });
```

**Comment by supelee** [comment]
@KDLGates Try contact.onConnecting( ), onIncoming( ) is only triggered for contact types like Queued Callbacks where the item is incoming and needs to be accepted before a connection begins connecting.  We should be clearer about that in our docs, sorry for the confusion.

**Comment by pukhrajbal** [comment]
@supelee Yes OnConnecting fires when a call is ringing BUT incoming phone number is not available in it. Is there a way that can be we can get access to incoming phone number.
This is available in ContactData once the call ends on OnEnded event.

**Comment by KDLGates** [comment]
@pukhrajbal What worked for me was using the Contact Flow editor in the admin dashboard, where you can add an attribute to the contact from the system's Caller ID attribute. Then, when the contact object arrives in JavaScript, it will have an attribute with the caller's phone number.

**Comment by pukhrajbal** [comment]
I updated the contact flow to add a SetContactAttribute box. 
![image](https://user-images.githubusercontent.com/1594975/29230441-eb25da06-7e97-11e7-8ef6-a331b112d32a.png)

It adds phone number to attributes in ContactData object. But for now ContactData is only showing up on OnEnded event. OnConnecting just shows contactId.

Here is code for checking available data 
 ```
connect.contact((contact) => {
   contact.onConnecting((a) => console.log('onConnecting', a));
   contact.onEnded((a) => console.log('onEnded', a));
});
```

Are you seeing contactData object in onConnecting?

**Comment by pukhrajbal** [comment]
contact..getAttributes() on OnConnecting provides this info.
