### ISSUE TITLE
Unable to pass agent object from a fucntion in javascript.

### ISSUE THREAD

**Issue by Wizard2436829** [aws/amazon-connect-streams#120]
So following are certain key points that I am trying to nail here.

1. Trying to call a method which takes an agent object but unable to call it.
2. Trying to get the incoming customer endpoint number but getting an error.

Am attaching my code.
[DemoPopUpWindow.txt](https://github.com/aws/amazon-connect-streams/files/3388841/DemoPopUpWindow.txt)

**Comment by ross-symbee** [comment]
Step 1 would be to make sure your inline javascript isn't being executed before the streams api has been loaded by placing the code in window.onload.

**Comment by Wizard2436829** [comment]
@ross-symbee ok even though I've done that it doesn't work. My principal task is to call SetAbandonedContactParams() from within handleContactEnded()....but the only constraint being handleContactEnded() accepts contact API object whereas SetAbandonedContactParams() demands a agent API object . How can we bring that Agent API object within the scope of handleContactEnded().

**Comment by ross-symbee** [comment]
Okay, great. Now when the Agent object gets set (it should be once per login) save it off to a variable that can be accessed from your SetAbandonedContactParams function. It's generally bad practice to use global vars but to get this working that'd be fine. Something like `connect.agent(function(agent) { window["connectAgent"] = agent; });` Then in SetAbandonedContactParams just include `var agent = window["connectAgent"];`.

**Comment by Wizard2436829** [comment]
@ross-symbee ya did try the global variable approach, although bad practice but still works in this case.
Thanks for the help though.
