### ISSUE TITLE
Is there any event for call hold?

### ISSUE THREAD

**Issue by VaibhavKakadeHS** [aws/amazon-connect-streams#133]
Is there any event to know the agent has put the call on hold? I know we can use connection.isOnHold() which will tell me the current state of the connection (if its on hold). But at a later point in time if the agent puts the call on hold, is there any way by which I know the phone call is on hold?
One way is to keep polling (using set interval) which is nonintuitive.

**Comment by jagadeeshaby** [comment]
Instead of interval you make use of contact onRefresh event handler which gets triggered on all the contact state changes including hold/resume. 

```
contact.onRefresh(() => {
  //  contact.getInitialConnection().isOnHold
 // if third party  -> contact. getSingleActiveThirdPartyConnection().isOnHold
})

```

**Comment by VaibhavKakadeHS** [comment]
Thanks for the reply @jagadeeshaby I will try this and update.

**Comment by VaibhavKakadeHS** [comment]
Hey, I have tried the mentioned solution and its working fine. Thanks for the help @jagadeeshaby :)
