### ISSUE TITLE
Accepted Calls Stalling at "Connecting..."

### ISSUE THREAD

**Issue by KDLGates** [aws/amazon-connect-streams#14]
Hello, @supelee and community.

Is there an issue with the following API code for accepting an incoming voice contact? It appears to work some times and not others, and is proving to be a huge frustration. When the accept attempt does not work, the subscribed "success" function for acceptCall is still fired, yet the CCP can still stall out while displaying "Connecting...". It then rolls over into the missed call state without ever reaching "Connected".

```
// Agent initializes, and persists into activeAgent.
var activeAgent;
connect.agent(function(agent) {
    console.log("Agent detected (init function fired)");
    activeAgent = agent;
});

connect.contact(function (contact) {
    contact.onConnecting(function (liveContact) {
        console.log("Contact detected");
        acceptCall();
    });
});

function getVoiceContact() {
    return activeAgent.getContacts()[0];
}

function acceptCall() {
    getVoiceContact().accept({
        success: function () {
            console.log("API reports call accepted successfully (this message is part of the 'success' function firing).");
        },
        failure: function (data) {
            console.log("Failed to accept the call. Troubleshooting data: " + data);
        }
    });
}
```

**Comment by HandyG52** [comment]
I am having this same issue.  I have been unable to define conditions for when a call successfully connects vs stalling out.  Any suggestions from developers or the community are appreciated.

Thanks

**Comment by KDLGates** [comment]
@HandyG52 

It looks like this call denying behavior was by design. I was missing the allowFramedSoftphone parameter in the initCCP function, and once I included it, not only did calls become accepted again (and reliably so), but lots of logging data appears in in the JavaScript console.

**Comment by HandyG52** [comment]
Thanks for the reply.  I can't get to my code right now, bit I'm pretty
confident that I have that parameter set and I still see this behavior
sometimes.  Seems like clearing the browser cache resolves the issue for a
while.
