### ISSUE TITLE
Google Chrome Update is breaking IFrame and turns into default phone panel

### ISSUE THREAD

**Issue by waqar125** [aws/amazon-connect-streams#154]
Hi,

we have some customizations on top of this connect streams built in phone panel. However just recently we have started to face this issue, after Chrome OS Update to Chrome Version 77.0.3865.105 (Official Build) (64-bit). 

the phone panel defaults to https://instance-name.awsapps.com/connect/ccp#/ 
i have replaced our instance name with instance-name for privacy.

**Comment by hfahlbusch** [comment]
Works on a mac with latest chrome (Version 77.0.3865.120 (Official Build) (64-Bit)) in my custom phone panel with an embedded ccp.
So it seems to be fixed or maybe an issue with your phone panel.

**Comment by waqar125** [comment]
so it looks like, if you click on 'shift' and then click on 'change agent states' on the customer phone panel.
it opens a new window with default (out of the box) phone panel......https://instance-name.awsapps.com/connect/ccp#/

**Comment by waqar125** [comment]
is there any way to block this? end users while working on so many tabs, can accidently click on changed states while shift is pressed (by accident)

**Comment by waqar125** [comment]
So this is an issue on chrome OS. Cannot reproduce on Mac .
