### ISSUE TITLE
How to accept an incoming call when having an another call on hold

### ISSUE THREAD

**Issue by clegeard** [aws/amazon-connect-streams#16]
Hi,
Is it possible to get an incoming call while you have another connection on hold?
If so, what do we have to do so that the call is routed to the agent?
Thanks

**Comment by supelee** [comment]
Hi clegard@,

Amazon Connect will not route a call to an agent who has an active call in progress or is in the after-call-work state.  The agent will only be routed contacts if they are in a routeable availability state such as "Available".
