### ISSUE TITLE
How to know if caller disconnects call

### ISSUE THREAD

**Issue by sandip31** [aws/amazon-connect-streams#160]
Hi
How to know if the caller has disconnects/hanged-up the call during the IVR before call actually routed to the agent.
Is there any callback to know or any way to know in the contact flow?

**Comment by camstuart** [comment]
I don't think this is possible. Connect Streams is only aware of the contact once the call is actually routed to the agent (assuming the agent is in a routable state).

To do something like this you would need to invoke a lambda function during your call flow, and that lambda could perhaps place an entry into dynamodb.

If your UI is using appsync, it would then have a mechanism of being aware of such scenarios

**Comment by ctwomblyamzn** [comment]
Thank you @camstuart for the helpful reply. This library is centered around modeling a single agent's interactions, and thus we have no information about contacts that have not yet been assigned to an agent. This is not accessible information in the context of this package. 

However, as @camstuart pointed out, you can become aware of disconnects in contact flows through a lambda function invocation.

**Comment by ctwomblyamzn** [comment]
This issue was answered, so it is being closed.
