### ISSUE TITLE
Transfer to another agent

### ISSUE THREAD

**Issue by camstuart** [aws/amazon-connect-streams#161]
Hi,

How do a create an `endpoint` of type: `EndpointType.AGENT`

I can create an `endpoint` by phone number using the static function: `Endpoint.byPhoneNumber()` 

But in my case, I would like to produce an endpoint by passing the target agent username (as agent arn's are not available)

My use case is to transfer between contacts agents internally. I already have a mechanism to display the target agents availability. But I would like to transfer to the target agents queue in a similar fashion to external transfer (without using quick connects)

**Comment by camstuart** [comment]
I attempted to create my own `endpoint` object like this:

```javascript
endpoint = {
        agentLogin: 'my-agent-username',
        endpointARN: 'my-agent-arn',
        endpointID: null,
        name: null,
        queue: null,
        type: connect.EndpointType.AGENT
      }
```

To obtain 'my-agent-arn' I created a quick call flow, and used the set working queue block and selected my agent username from the list. I wanted to be certain that there was not a separate queueARN for each agent. 

But unfortunately, this did not work either. With the error: 'InvalidStateException'

I really need to solve this, In my case quick connects will be too difficult to manage. I have 30 agents and 42 queues. So setting up the full agent list for each queue, and then managing them is not ideal

**Comment by camstuart** [comment]
In the end, the only way to achieve this was to use quick connects. But an AWS support engineer made a good recommendation to create a single (redundant) queue and attach the quick connects to those.

Then add that queue to the routing profile being used.

I then iterate through the queue and pull out the already constructed endpoint I need, and begin my transfer.

If anyone is interested, I can provide a sample

**Comment by jamesbyars** [comment]
@camstuart please do provide an example if you don't mind!

**Comment by sambathv** [comment]
@camstuart Please provide me with the sample. I need help with getting AWS ARN of quick connect. unable to transfer the call to quick connect.

**Comment by camstuart** [comment]
Sure:

Setup (in Amazon Connect)
1. Create a quick connect of type agent
2. Create a dedicated queue to hand your quick connect off, or choose an existing queue. 
3. Attach the quick connect you have created to the queue

In code (I do this work inside my agent refresh handler)

```typescript
try {
  let internalTransfers: Array<Object> = [];

  agent.getEndpoints(agent.getAllQueueARNs(), {
    success: (data) => {
      if (Array.isArray(data.endpoints)) {
        internalTransfers = data.endpoints.filter(ep => {
          return (ep.type === 'agent')
        })
      }
      this.agentUiState.internalTransferEndpoints = internalTransfers;
    },
    failure: () => {
      console.error("! failed getting getAllQueueARNs()");
    }
  });

} catch (e) {
  console.error('! unable to populate internal agent transfer list', e)
}
```

This will pick up all agent endpoints on all queues. I just attach them to a single queue in connect for ease of management.

Now this is done, I have an array of `endpoints` in the `internalTransfers` array of objects

**Comment by sambathv** [comment]
Thanks for your reply. Can you let me know how to get quick connect ARN?
I am trying to transfer the call to quick connect queue. Let me try the
option you have sent.

**Comment by camstuart** [comment]
If it's available it will be in the `endpoint` object, dump one out and see if it's there

**Comment by Harsha453** [comment]
Hi @camstuart , sometimes while transferring using quick connects i am getting failure in getEndpoints Api even i have proper Queue ARN.
[ERROR]: 'getEndpoints' API request failed: [object Object]'

**Comment by camstuart** [comment]
Hi @Harsha453 I have personally not seen this problem myself, but always interested in helping stamp out "intermittent" problems.

In the some of the documentation and examples I have seen, they are perhaps not taking full advantage of what `console.log` has to offer. The first argument is a label for the error (very important!) and any subsequent arguments are expanded prior to output.

Perhaps modify your call like so:

```JavaScript
console.log("'getEndpoints' API request failed:", error);
```
And your error object will be expanded to show more information, making trouble shooting a little easier.

Hopefully that will make the problem more obvious!

**Comment by Harsha453** [comment]
hi @camstuart, i appreciate you for taking time. I can see that if our queue doesn't configure with quickConnects, getEndpoints is throwing error. But even after i configure them also, they are not replicating the quickConnects data when i hit the api. A different queue whose having quickConnects earlier is giving data when i hit getEndpoints API, Can you look into this perspective.

**Comment by Harsha453** [comment]
Hi @camstuart, thank you for very much. Got the problem area
