### ISSUE TITLE
Getting error for agent.setState

### ISSUE THREAD

**Issue by VaibhavKakadeHS** [aws/amazon-connect-streams#162]
I have written following code
```javascript
connect.agent((agent)=> {
  agent.setState(connect.AgentStateType.OFFLINE, {
    success: () => {
      console.log("State change success");
    },
    failure: () => {
      console.log("State change failed");
    }
  });
});
```
I am getting the following error when I try setting agent state
```javascript
[ERROR]: 'putAgentState' API request failed
```
And failure callback is called. 

My use case is, I want to display two states on my dashboard : The current and the next.
Example: 
1. When the agent is available, current icon will show agent available and next icon will empty.
2. When the agent is talking with the user, current icon will show call in progress and next icon will show end call.
3. After the call is over and agent is in after call work state, current icon will show agent busy and next icon will available.

So I want to give ability to the agents to take next action by clicking some UI elements (some icon/button in this case) on my dashboard.

**Comment by hfahlbusch** [comment]
I guess it is your first parameter. There you are setting just a plain string:
`connect.AgentStateType.OFFLINE => "offline"`

Have a look at the documentation:
https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#agentsetstate

The first lines filter for the first routable state (in the example it's done by state **type**. You could also filter by state **name**, if you know the exact state you want.

`agent.getAgentStates().find((state) => state.name === 'nameYourState');`

**Comment by VaibhavKakadeHS** [comment]
@hfahlbusch Ahh my bad. I tried the above solution and it's working fine. Thanks for the reply.
