### ISSUE TITLE
Notification.requestPermission from iframe deprecated

### ISSUE THREAD

**Issue by MIKE133** [aws/amazon-connect-streams#17]
The embedded ccp iframe attempts to call Notification.requestPermission directly and as a result we receive the following warning in Chrome console:

Using the Notification API from an iframe is deprecated and will be removed in M61, around September 2017. You should consider requesting permission from the top-level frame or opening a new window instead. See [https://www.chromestatus.com/feature/6451284559265792] for more details.
 connect.NotificationManager.requestPermission @ lily_ccp_Prod_899828371c0911102feac318ba0a72696081e3ce.gz.js:sourcemap:23126

Is there a way to force CCP to perform the notification permission request in a separate window, instead of from within the iframe?

**Comment by ninjamike54** [comment]
We're aware of the issue, and we'll make an update to get this working again. Sorry about the long delay in commenting here.

**Comment by mschersten** [comment]
I'm also receiving this warning when testing on Linux, and I suspect it is related to a "Refused to display '<URL>' in a frame because it set 'X-Frame-Options' to 'sameorigin'" error preventing the site from working on Windows.

**Comment by ninjamike54** [comment]
Take a look at https://github.com/aws/amazon-connect-streams/issues/25 for details about X-Frame-Options errors; it's likely not related to notifications.

**Comment by jagadeeshaby** [comment]
Please feel free to reopen if the issue persists.

**Comment by bjm88** [comment]
We are seeing this. on latest Edge machines...
on latest build
connect-streams-min.64acf415.js:1 [Deprecation] Permission for the Notification API may no longer be requested from a cross-origin iframe. You should consider requesting permission from a top-level frame or opening a new window instead. See https://www.chromestatus.com/feature/6451284559265792 for more details.
