### ISSUE TITLE
Contact event not getting triggered in v1.4.2

### ISSUE THREAD

**Issue by boopathikumar018** [aws/amazon-connect-streams#183]
onConnecting() is not triggering when receiving incoming call tried both

`contact.onConnecting((contact) => { // contact is connecting })` // worked while using v1.2

`contact.onRefresh((contact) => { if(contact.isConnecting()){ // Contact is connecting } })`

**Comment by labelson** [comment]
Hmm, I am able to trigger onConnecting w/ an incoming call. Are you sure you are referencing the correct contact?

**Comment by boopathikumar018** [comment]
updated to latest version `v1.4.2-5-g99ca7d4` and working now
