### ISSUE TITLE
contact.onMissed() not being triggered

### ISSUE THREAD

**Issue by welshd1** [aws/amazon-connect-streams#188]
Hello,

All of the contact events I have set up are being fired properly except for contact.onMissed. This was mentioned in this issue: https://github.com/aws/amazon-connect-streams/issues/12

However, the resolution for that issue only answers the problem with onInbound vs. onConnecting, while the onMissed problem remains unanswered.

Love using AWS connect - thank you your help!

**Comment by labelson** [comment]
We are actively reviewing a patch for onMissed, so expect it to be fixed somewhat soon.

**Comment by ctwomblyamzn** [comment]
I'm going to mark this as closed, as this should be fixed with the patch above.
