### ISSUE TITLE
Iframe in the same window

### ISSUE THREAD

**Issue by k1p1l0** [aws/amazon-connect-streams#20]
Hello there!

I've embedded ACS into React and I have question how can I insert this url (https://{alias}.awsapps.com/connect/ccp) as an Iframe in the same window?

Because when I do it, I have tons of errors in the console.

<img width="1280" alt="screen shot 2017-09-05 at 6 21 19 pm" src="https://user-images.githubusercontent.com/7171026/30068631-09070846-9267-11e7-89cb-64bb6ad5f40d.png">

**Comment by joelbricker** [comment]
You have to white list the URL you are loading the iframe from in the Connect admin panel.  Also, I don't believe you can have ports on the white listed URL so you will have to run your dev server on a standard port or use Fiddler to redirect your URL request.

**Comment by k1p1l0** [comment]
Everything is okey there and it automatically opens a new window where I can login, but I want to have this window in my iFrame.

<img width="736" alt="screen shot 2017-09-05 at 6 36 34 pm" src="https://user-images.githubusercontent.com/7171026/30069340-290c1af8-9269-11e7-81c8-f8bcb0f28e76.png">

**Comment by joelbricker** [comment]
Try using HTTPS.

**Comment by joelbricker** [comment]
Oh wait, sorry.  I replied from the e mail and didn't see the second half of your comment regarding the login window.  There is no way, right now, to have that login come in am Iframe.  I think there is OAUTH authentication planned for the future, but we are stuck with the current login flow for now.

**Comment by k1p1l0** [comment]
Okey. Thank you.
