### ISSUE TITLE
Amazon Connect Login Page in iFrame not the same size as maximum CCP app width

### ISSUE THREAD

**Issue by sromocki** [aws/amazon-connect-streams#22]
The Amazon Connect Login page that gets rendered in an iframe is larger than the maximum amount of width the CCP app will expand to, which leads to a css width discrepancy.  Could you all create a version of the login page that is more compatible with the embedded CCP app in a iframe approach?  Thanks, Sean.

**Comment by ninjamike54** [comment]
Is this the login page that is opened with the popup logic? The login page itself shouldn't work inside a frame (hence needing the popup) since it enforces X-Frame-Options (SAMEORIGIN).

**Comment by sromocki** [comment]
@ninjamike54 I had a Chrome extension that was negating the X-Frame-Options so I could have the login page show up in the iFrame, which obviously isn't supported.  I'm just gonna close this one.
