### ISSUE TITLE
All connections are destroy will trying to destroy third party connection

### ISSUE THREAD

**Issue by markwinap** [aws/amazon-connect-streams#24]
Same Result using destroy() with the following connections

getThirdPartyConnections() // / Will trying to destroy() the third party connection [0]
getSingleActiveThirdPartyConnection()
getConnections() // Will trying to destroy() the third party connection [2]

**Comment by efh365** [comment]
Can you please clarify what is happening? Im not following the description or title

**Comment by jagadeeshaby** [comment]
Please feel free to reopen if the issue persists.
