### ISSUE TITLE
Call transfers and quick connect support

### ISSUE THREAD

**Issue by markwinap** [aws/amazon-connect-streams#27]
I noticed that there is no support for quick connects and call transfer options.

**Comment by dbraynard** [comment]
@markwinap, are you referring to the ccp where it has a Quick Connects (or ContactController) and a refresh button, but nothing happens when it is presssed?

**Comment by markwinap** [comment]
Hi, I'm referring to the ccp aget API. Where there is no documentation or support t get the list of quick connects

**Comment by efh365** [comment]
It seems there is a missing function in the documentation. You can get the quick connects by calling agent.getEndpoints(outboundQueueName)

Quick Connects are determined based on the outbound queue on the call. You can get the outbound queue from agent.getRoutingProfile().

**Comment by jagadeeshaby** [comment]
Here is the small snippet of code which pulls the quick connects and initiates the transfer call flow. 

var agent = new lily.Agent();

agent.getEndpoints(agent.getAllQueueARNs(), {
	success: function(data){ 
		console.log("valid_queue_phone_agent_endpoints", data.endpoints, "You can transfer the call to any of these endpoints");
	},
	failure:function(){
		console.log("failed")
	}
});

agent.getContacts(lily.ContactType.VOICE)[0].addConnection(any_valid_queue_or_phone_or_agent_endpoint, {
    success: function(data) {
       alert("transfer success");
    },
    failure: function(data) {
       alert("transfer failed");
    }
});

Hope this helps!

**Comment by akirsman** [comment]
Hi jagadeeshaby, who's "lily" in the snippet above? I'm having trouble finding ContactType.VOICE. I assumed that lily == window.myCPP but seems not to contain any ContactType enum... Thanks

**Comment by jagadeeshaby** [comment]
its basically a namespace, you will get this once you include the connect streams library. 

Please use "connect" instead of "lily"

`connect.ContactType.VOICE` . this should return "voice" 

Please let me if this helps.

**Comment by jagadeeshaby** [comment]
Please feel free re-open if the issue persists.

**Comment by Harsha453** [comment]
Hi @jagadeeshaby, sometimes while transferring using quick connects i am getting failure in getEndpoints Api even i have proper Queue ARN.
[ERROR]: 'getEndpoints' API request failed: [object Object]'

**Comment by bhanuyandraJava** [comment]
can we transfer the to another quick connect, agent one receives a quick connect call --> transfers to agent two using quick connect
