### ISSUE TITLE
TypeError: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by joshuaascott** [aws/amazon-connect-streams#3]
After creating the javascript file using make and creating a page to call connect.core.initCCP(), you can view the CCP embedded with Chrome and it functions properly. However IE has issues and one can not change the status from the page.

<img width="772" alt="error" src="https://cloud.githubusercontent.com/assets/2485451/26418657/064395e4-408b-11e7-8bc6-5b24f775c100.png">

**Comment by autrey** [comment]
Only Chrome and Firefox are supported at this time. IE does not use the standard webRTC implementation used by the supported browsers. Edge 15 supposedly supports standard WebRTC, but my up-to-date Windows box is on EdgeHTML 14.14393. Regardless, only Chrome and Firefox are officially supported right now.
