### ISSUE TITLE
Queues

### ISSUE THREAD

**Issue by tatskah** [aws/amazon-connect-streams#31]
Hi,

Is that possible to find a contact from agent queues/connections with a phone number?

**Comment by ninjamike54** [comment]
We don't have anything on the streams API to search for historical contacts (the streams API is intended for real-time, single agent information), but the Contact search functionality in the administrative website will let you search for historical contacts.

**Comment by jagadeeshaby** [comment]
Closing the issue as it's not applicable for the streams API.
