### ISSUE TITLE
'make' command not generating connect-streams-${VERSION}.js 

### ISSUE THREAD

**Issue by bhavitha7** [aws/amazon-connect-streams#35]
it is only generating amazon-connect-${version}.js

**Comment by ninjamike54** [comment]
As far as I'm aware, this is intended. The documentation says:

Run the Makefile to generate amazon-connect-${version}.js, then copy this file into your application or host it in an Amazon S3 bucket behind Amazon Cloudfront.
Then below, it says "Once you download streams, change into the directory and build it...This will generate a file called connect-streams-${VERSION}.js"

I think this is just a typo in our documentation, I'll get that fixed.

**Comment by jagadeeshaby** [comment]
With the new NPM build system support this is no more an issue. please feel free to re-open if the issue exists.
