### ISSUE TITLE
get contact information from lambda

### ISSUE THREAD

**Issue by aliatry1** [aws/amazon-connect-streams#42]
Hi, 
I'm trying to get contact information such as ID or Phone Number from lambda. I've placed one lambda in my contactFlow after the start block. I have some issues now:
My lambda doesn't invoke when I receive the call!
Do I need to enable Kinesis in my Amazon connect instance to use stream Api?
How do I use stream api from lambda?I can't find how to use connect-streams's functions inside my code! for example when you want to use "fs", you use the module by using "const fs = require'fs' ".how about for connect-stream?!
please help!

**Comment by autrey** [comment]
The streams API is for embedding the softphone in a CRM or creating a customized version of the softphone (CCP). It doesn't run inside a Lambda function. You would use the streams library to add the CCP to a webpage, communicate with a CRM, respond to events from the CCP/softphone, etc. 

Lambdas in Connect are another matter. Once your Lambda works on its own, meaning you can test it via unit tests and then integration test it, try to run a sample test from within the Lambda management UI. If everything works with Lambda at that point, then your most likely problem is permissions. In order for Lambda to be executed by a Connect contact flow, you need to run the CLI command on this [documentation page](https://docs.aws.amazon.com/connect/latest/adminguide/connect-lambda-functions.html).

Best of luck. Feel free to respond with other questions.

**Comment by aliatry1** [comment]
Thank-you Autrey for your answer.
