### ISSUE TITLE
contact::init and  agent::init event handler failed github

### ISSUE THREAD

**Issue by srinivasanV2-hexaware** [aws/amazon-connect-streams#46]
Hi please check, im getting error when trying to get incoming call logs. Can i know the issue type

**Comment by autrey** [comment]
Is there any way you could provide some more context or a code sample? That would be helpful in trying to diagnose what’s going on

**Comment by srinivasanV2-hexaware** [comment]
<script src="./amazon-connect-v1.2.0-2-g5fc44af.js"></script>
    <script type="text/javascript">
        var ccpUrl = "https://hexinno.awsapps.com/connect/ccp";
        connect.core.initCCP(containerDiv, {
            ccpUrl: ccpUrl,
            loginPopup: true,
            softphone: {
                allowFramedSoftphone: true
            }
        });
connect.contact(function(contact) {
  console.log("Get Call Details");
  var activeConnection = contact.getActiveInitialConnection();
  var contactId = activeConnection['contactId'];
  var connectionId = activeConnection['connectionId'];
  var conn = new connect.Connection(contactId, connectionId);
  var customerNo = conn.getEndpoint().phoneNumber;
  
  console.log("Set Customer Phone Number");
  $("#callerNo").empty();
  $('#callerNo').append(customerNo);
  document.getElementById('phoneNo').value = customerNo;
  console.log("Get Call Attributes");
  var callAttributes = contact.getAttributes();
  console.log("Set Call Attributes");;
  $("#attributes").empty();
  Object.keys(callAttributes).forEach(function(key) {
    
    console.log("Adding Attribute To Table");
    $('#attributes').append( "<tr> <td>"+callAttributes[key]["name"]+"</td> <td>"+callAttributes[key]["value"]+"</td> </tr>" );
  });
});
   
    </script>

**Comment by mschersten** [comment]
What error are you getting?  Do any of your console.logs show up?

**Comment by jagadeeshaby** [comment]
Hope this issue is fixed . Please feel free to reopen if it persists.

**Comment by amitrjaiswal1** [comment]
I am getting below error in log.
[ERROR]: 'agent::init' event handler failed.

**Comment by Pianist038801** [comment]
I get this error. 
[ERROR]: 'contact::init' event handler failed.

**Comment by alexgurr** [comment]
From my experience with this issue, it's caused by an exception in your own code, thrown within a streams function.

In my specific example, I had some code to trigger a notification inside a callback:

```
connect.contact(onIncomingCall);

const onIncomingCall = () => {
  notify(); // This was throwing an exception which was being swallowed by streams code and showing a generic init error
}
```

My recommendation is to comment out a line at a time any code you might have in a callback function until you find the culprit. You won't know the underlying error because the streams error handler catches it.
