### ISSUE TITLE
Transfer a call to an agent

### ISSUE THREAD

**Issue by SherifIssa** [aws/amazon-connect-streams#54]
How do I transfer a call to another agent or queue using the Stream API?

**Comment by jagadeeshaby** [comment]
As of Today StreamJS allows the transfer call functionality with the Quick connects(queue/agent/External phone number)! 

Here is the small snippet of code which pulls the configured quick connects and initiates the transfer call flow.

```
var agent = new lily.Agent();

agent.getEndpoints(agent.getAllQueueARNs(), {
success: function(data){
    console.log("valid_queue_phone_agent_endpoints", data.endpoints, "You can transfer the call to any 
      of these endpoints");
},
failure:function(){
     console.log("failed")
}
});
agent.getContacts(lily.ContactType.VOICE)[0].addConnection(any_valid_queue_or_phone_or_agent_endpoint, {
   success: function(data) {
      alert("transfer success");
  },
  failure: function(data) {
    alert("transfer failed");
  }
});

```

Hope this helps!

**Comment by CiscoKidxx** [comment]
For anyone else stumbling across this, you have to destroy the agent connection in the success block of the addConnection.

Example:
```
          $contact.getAgentConnection().destroy({
            success: function() {
              console.log(`destroying ${$contact}`);
              resolve();
            },
            failure: function(error) {
              reject(console.log(error));
            }
          });
```

**Comment by ManojKatta123** [comment]
> As of Today StreamJS allows the transfer call functionality with the Quick connects(queue/agent/External phone number)!
> 
> Here is the small snippet of code which pulls the configured quick connects and initiates the transfer call flow.
> 
> ```
> var agent = new lily.Agent();
> 
> agent.getEndpoints(agent.getAllQueueARNs(), {
> success: function(data){
>     console.log("valid_queue_phone_agent_endpoints", data.endpoints, "You can transfer the call to any 
>       of these endpoints");
> },
> failure:function(){
>      console.log("failed")
> }
> });
> agent.getContacts(lily.ContactType.VOICE)[0].addConnection(any_valid_queue_or_phone_or_agent_endpoint, {
>    success: function(data) {
>       alert("transfer success");
>   },
>   failure: function(data) {
>     alert("transfer failed");
>   }
> });
> ```
> Hope this helps!

HI @jagadeeshaby ,

can you clarify , what is the meaning of **lilly**

**Comment by jagadeeshaby** [comment]
lily is the connects old namespace. Recommendation here is to use "connect" namespace in place "lily"

**Comment by jagadeeshaby** [comment]
Please feel to reopen if you need any further assistance.

**Comment by faizaanshah** [comment]
Hey @jagadeeshaby I have been trying to transfer call to an agent via quick connects from my CCP. I have added some queues and agents in my quick connect. 

Now queues show up in quick connect in CCP but agents don't , no matter how much I refresh. 

Any idea?

**Comment by Harsha453** [comment]
Hi @jagadeeshaby, sometimes while transferring using quick connects i am getting failure in getEndpoints Api even i have proper Queue ARN.
[ERROR]: \'getEndpoints\' API request failed: [object Object]'

**Comment by Selva-Guru** [comment]
Hi, how do we can do Warm transfer to another available quick connect agent? Could you please help me with some code snippet.

**Comment by faizaanshah** [comment]
> Hi, how do we can do Warm transfer to another available quick connect agent? Could you please help me with some code snippet.

You can get a good idea from this cheat sheet
https://github.com/amazon-connect/amazon-connect-streams/blob/master/cheat-sheet.md
