### ISSUE TITLE
Closing login page

### ISSUE THREAD

**Issue by mschersten** [aws/amazon-connect-streams#56]
One of the issues people have had with the login process is that the login page remains open after logging in, and converts to a CCP that needs to be closed manually so the agent can use the custom CCP.

Would it be possible to get the handle of the login popup to use window.close() to close it?

First, we load the CCP or login with connect.core.initCCP().  I can find that in the Streams API source at (in my build) line 20373, with the login popup at line 20465:

`connect.core.getPopupManager().open(loginUrl, connect.MasterTopics.LOGIN_POPUP);`

Then starting on line 17883, I find this:

```
connect.PopupManager.prototype.open = function(url, name) {
  var then = this._getLastOpenedTimestamp(name);
  var now = new Date().getTime();

  if (now - then > ONE_DAY_MILLIS) {
     var win = window.open('', name);
     if (win.location !== url) {
        window.open(url, name);
     }
     this._setLastOpenedTimestamp(name, now);
  }
}
```

So can we find someway to get a hold of that "win" var, to then do win.close() after the agent is logged in?  We would probably not want to return that from connect.core.initCCP(), but can we do something like this?

```
var loginPopup = connect.core.getLoginPopup()
loginPopup.close()
```
This was a late-night thought, and I haven't tried anything from this yet.  Any input is appreciated.

**Comment by AndySteel-kcom** [comment]
I used this technique, calling the following code immediately after the streams api has initialised.

        const w = window.open('', connect.MasterTopics.LOGIN_POPUP);
        if (w) {
          w.close();
        }

Works for me without side effects.

**Comment by mschersten** [comment]
That works perfectly for me.  Thanks!

**Comment by AbdulQayyumaq** [comment]
@AndySteel-kcom Thank you.
I am a newbie can you please help me in it as where to use this code? you said right after the streams api has initialized. is it index.js or where?
@mschersten please guide as you have done..
Like this?
```
connect.core.initCCP(containerDiv,
{

 });
const w = window.open('', connect.MasterTopics.LOGIN_POPUP);
    if (w) {
      w.close();
    }
```

**Comment by mschersten** [comment]
Hi @AbdulQayyumaq,

I'll give a brief explanation of how that worked, but I believe this has been replaced by a new configuration option.

In the old way, you would initialize Connect, and then subscribe to agent events, and then close the window in the agent event subscription:

```
connect.core.initCCP(containerDiv,{});
connect.agent(subscribeToAgentEvents);
function subscribeToAgentEvents(agent) {
    const w = window.open('', connect.MasterTopics.LOGIN_POPUP);
    if (w) {
      w.close();
    }
};
```

But now there is a method to autoClose, search the documentation for "autoclose" and you'll find options.loginOptions.autoclose, and options.loginPopupAutoClose.  So I think you can just do

```
connect.core.initCCP(containerDiv, {
    loginPopupAutoClose: true, 
    loginOptions: {
      autoClose: true
    }
});
```

With all the other required options, of course.

**Comment by AbdulQayyumaq** [comment]
Thank you. I have done it. yeah there is an option of autoClose but it doesn't working as login popup got open in a new window but couldn't get closed.
i have used  this solution its working only in Chrome but not in Edge.
