### ISSUE TITLE
Makefile not working on Windows (not compatible with nmake)

### ISSUE THREAD

**Issue by extmchristensen** [aws/amazon-connect-streams#57]
The supplied makefile does not work on windows with visual studio. This is what happens if I run it in a Visual Studio command shell using "nmake":

```
Microsoft (R) Program Maintenance Utility Version 14.13.26131.1
Copyright (C) Microsoft Corporation.  All rights reserved.

makefile(6) : fatal error U1000: syntax error : ')' missing in macro invocation
Stop.
```

**Comment by jagadeeshaby** [comment]
Alternatively we can go with the new NPM gulp build system to generate the assets - https://github.com/aws/amazon-connect-streams/pull/61 -  Once merged please refer the documentation for the usage.

**Comment by extmchristensen** [comment]
Resolved by latest merge
