### ISSUE TITLE
Subscribe methods do not return subscription object

### ISSUE THREAD

**Issue by phmiller** [aws/amazon-connect-streams#58]
The documentation at [https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#event-subscription](https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#event-subscription) and at [https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#note](https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#note) states that the event bus and event bus helper methods (.on*) for subscribing to events return a subscription object. Which later on you can call .unsubscribe() on to unsubscribe from future notifications.

This does not match the behavior or source code. In the [event.js](https://github.com/aws/amazon-connect-streams/blob/master/src/event.js) file, if you look at the EventBus subscribe's method and track it through, you can see the problem:

`
   /**
    * Subscribe to the named event.  Returns a new Subscription object
    * which can be used to unsubscribe.
    */
   EventBus.prototype.subscribe = function(eventName, f) {
      connect.assertNotNull(eventName, 'eventName');
      connect.assertNotNull(f, 'f');
      connect.assertTrue(connect.isFunction(f), 'f must be a function');
      return this.subMap.subscribe(eventName, f);
   };

   /**
    * Add a subscription for the named event.  Creates a new Subscription
    * object and returns it.  This object can be used to unsubscribe.
    */
   SubscriptionMap.prototype.subscribe = function(eventName, f) {
      var sub = new Subscription(this, eventName, f);
      this.subIdMap[sub.id] = sub;
      var subList = this.subEventNameMap[eventName] || [];
      subList.push(sub);
      this.subEventNameMap[eventName] = subList;
   };`

So the SubscriptionMap subscribe function is not returning anything (undefined). Looks like it needs a return statement at the end to return the 'sub' object.

The .on* methods like agent.onRefresh use the event bus subscribe under the covers.

I would like this functionality to work to add better tear down code when someone logs out of the CCP and in general be able to better manage event subscriptions in my code.

**Comment by jagadeeshaby** [comment]
Issue is resolved and fix is available on 1.3.2 version. 

Closing the issue. please feel free to re-open if the issue persists
