### ISSUE TITLE
Get Contact Number from an Incoming Call

### ISSUE THREAD

**Issue by bizcloudexperts** [aws/amazon-connect-streams#7]
Is there any way to get the contact number from an inbound call using the Contact API provided in the connect streams API doc? I am not sure if we can get the contact number from the given API event functions.

**Comment by pukhrajbal** [comment]
@bizcloudexperts were you able to get number from incoming call?

**Comment by mann2107** [comment]
@bizcloudexperts Any update guys ?

**Comment by pukhrajbal** [comment]
@mann2107 refer to this https://github.com/amazon-connect/amazon-connect-streams/issues/12#issuecomment-321870815

**Comment by chawes13** [comment]
I was able to reference the contact's phone number without adding a custom attribute in the Contact Flow:
```js
contact.onConnecting((c) => {
  const { phoneNumber } = c.getActiveInitialConnection()?.getEndpoint()
})
```
@pukhrajbal Please let me know if you have concerns with this approach, as my understanding of `getActiveInitialConnection` is pretty limited
