### ISSUE TITLE
Unable to retrieve the Contact.getState()

### ISSUE THREAD

**Issue by vdineshmca** [aws/amazon-connect-streams#72]
Hi,

From the documentation, mentioned the way to retrieve the Contact state from the Contact object but real time we are unable to retrieve the Contact State.

https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#contactgetstate

Anyone help us how to retrieve the Contact State from Connect Stream.

**Comment by jagadeeshaby** [comment]
Is there a script that you're trying to execute?

contact.getState()- will always return the current ongoing contact state. like - Incoming, Missed etc.

**Comment by jagadeeshaby** [comment]
Please feel free to reopen the issue.
