### ISSUE TITLE
agent.mute silently fails after softphone is refreshed on voice interaction

### ISSUE THREAD

**Issue by amollerson** [aws/amazon-connect-streams#75]
This behavior is seen both with the Connect CCP softphone and using the amazon connect streams api.

If a voice interaction is active and the window/frame that the softphone or a softphone using the API lives in is refreshed the mute/unmute API calls silently fail for the remainder of the interaction.

**Comment by jagadeeshaby** [comment]
Please refer the [Issue](https://github.com/aws/amazon-connect-streams/issues/33)

Unfortunately I don't have any details about what exactly we will do here (or when it'll happen).

**Comment by jagadeeshaby** [comment]
For now this behavior is expected as it's mentioned here https://github.com/aws/amazon-connect-streams/issues/33.
