### ISSUE TITLE
Outbound call!

### ISSUE THREAD

**Issue by aliatry1** [aws/amazon-connect-streams#77]
Hi, 

I have an embedded CCP inside my app and I want to make an outbound call by clicking a number in the page. I was able to do this by calling Amazon Connect API. I also tried to do this with amazon-connect-streams but it didn't work. here is my code 

        `connect.agent(function (agent){
               const endpoint = "+81XXXXXXXX";
               agent.connect(endpoint , {
                     queueARN : "arn:aws:connect:ap-southeast-2:XX:instance/XXX/queue/XXXX",
                     success : function(){console.log("Success call!!!!!!")},
                     failure : function(){console.log("Call failed!!!!!!!")}
              });
        });` 
Output: 
Call failed!!!!!!!
[ERROR]: 'createOutboundContact' API request failed: [object Object]

Can anyone help me with this issue? Thank-you

**Comment by rddbank4** [comment]
Hi.

endpoint is object, not phone number string.  So you have to make endpoint
by utility function before you call agent.connect()

example)
var endpoint = connect.Endpoint.byPhoneNumber('+81********');

hope this would be help.


2018年8月15日(水) 17:50 aliatry1 <notifications@github.com>:

**Comment by aliatry1** [comment]
Awesome! Thank-you!!

**Comment by rpaulojade** [comment]
Hi I'm also having the same issue. It worked for a while but then all of a sudden it stopped.
Below is our code.

```
const endpoint = this.connect.Endpoint.byPhoneNumber(phoneNumber);
    agent.connect(endpoint, {
      success: () => {console.log('success')},
      failure: () => {console.log('failures')}
    })
```

**Comment by Selva-Guru** [comment]
Hi, I'm trying to make an outbound call (Agent to Agent) using quick connect. In my amazon connect dial panel, I am not able to see any quick connect agent but it is available when transferring existing contact. Can anyone help on this.

window.myCPP.agent.connect(data.endpoints[qcAgentID], {
	success: function(data) {
		console.log("dial to quick connect - success "+data);
	},
	failure: function(data) {
		console.log("dial to quick connect - failed");
	}
});	


And below is the error log.

connect-streams-min.85524545.js:1 [2020-11-26T10:51:49.585Z] [ERROR]: 'createOutboundContact' API request failed
connect-streams-min.85524545.js:1 [2020-11-26T10:51:49.586Z] [ERROR]: Failed to handle AWS API request for method createOutboundContact
amazon-connect-1.5.1-2-g1037b86.js:21229 [2020-11-26T10:51:49.585Z] [ERROR]: 'createOutboundContact' API request failed
connect-streams-min.85524545.js:1 [2020-11-26T10:51:49.586Z] [ERROR]: Failed to handle AWS API request for method createOutboundContact
amazon-connect-1.5.1-2-g1037b86.js:21229 [2020-11-26T10:51:49.586Z] [ERROR]: Failed to handle AWS API request for method createOutboundContact

**Comment by nmiddleweek** [comment]
@Selva-Guru - if you console.log(data) in your failure handler it will give you a bit more information about why the failure is happening.
