### ISSUE TITLE
Unable to answer call from the embedded CCP

### ISSUE THREAD

**Issue by yann140573** [aws/amazon-connect-streams#8]
Hi,

I am using CCP embedded on SalesForce UI.
For some reason I am unable to answer the call. The status is changing to "Connecting", but seems like call remains in the queue. 
I created short video that demonstrates the issue:

https://drive.google.com/open?id=0B6xKEeS9aV0LdVNzX0xsZ3F1TmM

I don't have any problem to answer the call when I am using CCP on the Amazon Connect environment.

**Comment by supelee** [comment]
Hello yann140573,

You may need to specify `allowFramedSoftphone: true` in your softphone parameters to `connect.core.initCCP( )`, see here:
https://github.com/aws/amazon-connect-streams#connectcoreinitccp

Without this flag, softphone initialization is suppressed in framed CCP windows.

Thanks,

Lain

**Comment by yann140573** [comment]
Thank you Lain. It works.
