### ISSUE TITLE
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.

### ISSUE THREAD

**Issue by CiscoKidxx** [aws/amazon-connect-streams#81]
Inbound call ringer is not audible due to chrome's new autoplay policies. The policy requires a "user gesture" before allowing media to pass. I cannot figure out how to satisfy that requirement for inbound calls to function correctly.

Has anyone come up with a solution for this?

**Comment by bigsapper** [comment]
What version of Chrome was this introduced?

**Comment by mschersten** [comment]
I feel like this has been here for a while (April 2018?).  This is only on the first call, correct?  After that, the agent has probably interacted with the softphone at some point (ie, to accept or end the call) so the ringer should play on subsequent calls.

We use logic, for other reasons, to prevent users from being set to available when they first log in.  The effect of this is to require them to interact with the softphone to set their status, so when the first call comes in Chrome is ready to allow it to play.

I don't think there's any way around this except to "trick" the user into interacting before they first get a call, and I think the only way to do that is to set them away from available when they first start.

**Comment by hfahlbusch** [comment]
I guess this behavior changed in April 2018. I was a little bit confused by the error message while I was trying to fix another bug in my code.

The following link show delegation for autoplay to an iframe: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#iframe

There could be made additional fixes to the play() method to check that it has permission - like suggested in the link before:

`var promise = this._audio.play();

if (promise !== undefined) {
  promise.then(_ => {
    // Autoplay started!
  }).catch(error => {
    // Autoplay was prevented.
    // Show a "Play" button so that user can start playback.
  });`

The pull request should improve the rights delegation, so when the page already has permission it will be passed to the iframe.
