### ISSUE TITLE
contact.onIncoming vs contact.onConnecting

### ISSUE THREAD

**Issue by mschersten** [aws/amazon-connect-streams#85]
Maybe this has been addressed before, but the documented contact.onIncoming() doesn't appear to ever be called.  Instead, any actions on a contact before the agent answers need to be done in contact.onConnecting().

**Comment by jagadeeshaby** [comment]
Here is the difference between the two. 

 contact.onIncoming - Triggered for the Queue callbacks.
 contact.onConnecting -> Triggered for the normal inbound calls.

**Comment by waqar125** [comment]
and in case of manual Dial outs, would it be contact.OnIncoming as well?

**Comment by dnovicki** [comment]
onConnecting() is not covered in the documentation or even listed in index.ts file in source. It seems the pattern listed above by @jagadeeshaby isn't intentional. I am also confused why softphone uses contact.onRefresh() for incoming calls. Solid examples and more detailed documentation would be helpful

**Comment by jagadeeshaby** [comment]
Thanks for the feedback on the documentation will update the same. 

Just to provide more insights here. 

contact.onRefresh() -> is the multiplexed handler (event handler) for all the changes happening over contact like contact status stage, Internal connection updates, new third party connection addition  etc. (Any additional future attribute updates)

-  To be more specific this event handler is triggered with the new contact instance for all the differences that we see on the contact snapshot (agent snapshot). 

Best use case -> To know When to activate a 3 way connection (third party connection) view on CCP -> Bind a  onRefresh event handler on contact and look for a non null value on getSingleActiveThirdPartyConnection to gather the possible new third party addition. 

and also it's futuristic in nature due it's generic implementation as compared to very specific contact status change event handlers. (subset)

Ex: contact.onConnecting is a dedicated event handler which is triggered only when contact status value is connecting rather onRefresh is triggered for all the contact updates 

so below 2 snippets are identical in terms of handling connecting use case. 

`contact.onConnecting((contact) => {
    // contact is connecting
})`

`contact.onRefresh((contact) => {
   if(contact.isConnecting()){
     // Contact is connecting 
  }
})`

And regarding the onConnecting vs onIncoming ->  yes it is bit confusing in terms of not having this for normal calls rather only for Queue callbacks.  (I'm not so sure about the decision here),

For now best way to deal with this is 

```
connect.contact(function(contact) {
   if(contact.getType() === connect.ContactType.QUEUE_CALLBACK ) {
         contact.onIncoming(() => { // });
    } else if (contact.getType() === connect.ContactType.VOICE) {
       contact.onConnecting(() => {});
     }
});
```

**Comment by jagadeeshaby** [comment]
Please feel free to re-open if you need further assistance.
