### ISSUE TITLE
'destroyContact' API request failed

### ISSUE THREAD

**Issue by yann140573** [aws/amazon-connect-streams#9]
Hi,

I am running the following scenario:

1. Call to the IVR. 
2. Call routed to the agent CCP
3. Call automatically accepted using contact.accept()
4. After 10 seconds I am trying to disconnect call using contact.destroy() and getting the following error:

[2017-07-27T20:49:11.939Z] [ERROR]: 'destroyContact' API request failed: Error
ERROR @ lily_ccp_Prod_8998283….gz.js:22343
Logger.addLogEntry @ lily_ccp_Prod_8998283….gz.js:22570
(anonymous) @ lily_ccp_Prod_8998283….gz.js:25513
(anonymous) @ lily_ccp_Prod_8998283….gz.js:23446
EventBus.trigger @ lily_ccp_Prod_8998283….gz.js:23444
Conduit._dispatchEvent @ lily_ccp_Prod_8998283….gz.js:23759
(anonymous) @ lily_ccp_Prod_8998283….gz.js:22770
16:49:12.733 

Any ideas?

Thank you.
Yan

**Comment by supelee** [comment]
Hi yann140573,

Can you reproduce the issue, then execute "connect.getLog().download()", or click the "Download Logs" button in the CCP to gather logs and attach them to this issue?

Thanks!

Lain

**Comment by yann140573** [comment]
[agent-log.txt](https://github.com/aws/amazon-connect-streams/files/1181351/agent-log.txt)
Done!

**Comment by supelee** [comment]
Hi yann140573,

Thanks for the logs.  I believe the destroyContact method was deprecated at some point and was not removed from this API.  You should use destroy() on the initial connection of the contact instead:
```
contact.getInitialConnection().destroy()
```

If you are managing a three way call, you will want to destroy the third party connection as well:

```
var initialConnection = contact.getInitialConnection();
var thirdParty = contact.getSingleActiveThirdPartyConnection();
if (initialConnection) {
    initialConnection.destroy();
}
if (thirdParty) {
    thirdParty.destroy();
}
```

The contact is destroyed when its constituent connections are destroyed (with the exception of the agent connection).
 
Sorry for the confusion!  We will remove this deprecated Contact.destroy( ) method in a future iteration.

Lain

**Comment by supelee** [comment]
Another point of notice: you can destroy the agent connection in a three way call scenario.  This will leave the third party and initial connections together while the contact is destroyed.  This scenario is sometimes referred to as a "warm transfer" since the agent is initially connected and then leaves the contact.
