### ISSUE TITLE
Unable to answer call in AmazonConnect

### ISSUE THREAD

**Issue by ManojKatta123** [aws/amazon-connect-streams#92]
I am unable to incoming call in amazon connect ,My CCP
 connect.core.initCCP(containerDiv, {
    ccpUrl:'https://XXXXXXXX-XXXX-XXXXXXX.awsapps.com/connect/ccp',
    loginPopup: true,         				
    softphone: {             				
        allowFramedSoftphone: false,													
    }
});
When i close the CCP window which is used for login , I am facing this issue 
the above issue is not happening when i open CCP window is open
I am loading CCP in my application through Iframe

**Comment by ManojKatta123** [comment]
Works fine in Mozilla..by loading CCP in both IFrame and CRM

**Comment by alxx** [comment]
I am also unable to accept incoming calls as well, using the iframe CCP. It works fine using the stock CCP.

I get the incoming call, I press Answer, and then it only says "Connecting" and it times out after a few seconds with `MissedCallAgent`.

I've tried this in Chrome 71 and in Firefox 65.

**Comment by alxx** [comment]
I got it: you need to have this **undocumented** flag set to true:

`allowFramedSoftphone: true`

Why such a crucial element was left out of the documentation I shall never understand.

**Comment by ManojKatta123** [comment]
Hi @alxx  the issue is due to Microphone .. Iframe dont support use of  Microphone  So load both iframe and connector in same window .. so when when you click on answer .. the microphone will be accessed from CCP
