### ISSUE TITLE
Type Definition: agent.getContacts() requires parameter "contactTypeFilter"

### ISSUE THREAD

**Issue by aguecida** [aws/amazon-connect-streams#99]
The method `agent.getContacts()` has one optional parameter, `contactTypeFilter`. However, in the TypeScript type definition file, this parameter is mandatory gives the error "index.d.ts(158, 21): An argument for 'contactTypeFilter' was not provided." if not provided.

**Comment by jagadeeshaby** [comment]
https://github.com/aws/amazon-connect-streams/blob/master/src/index.d.ts#L308. 

Thanks @aguecida  for the fix. 

closing the issue.
